### ISSUE TITLE
Strange Error About Missing Path

### ISSUE THREAD

**Issue by AusarAtef** [Lazyneer/MvM-Upgrades-Vscript-Converter#1]
I made some changes to pl_swiftwater so that bots wouldn't get stuck on the gates and while the map runs perfectly fine trying to convert it throws an error that it can't find a part of the path.

![51869114 18999988_image](https://github.com/Lazyneer/MvM-Upgrades-Vscript-Converter/assets/8691748/bec1b187-dddd-4a82-a9e6-dd2d8cda3d92)

The actual folder it's looking for is nonexistent and adding the folder does nothing as it gets deleted. I've run other maps that were re-compiled with no issue, it's just swiftwater giving an error.

**Comment by Lazyneer** [comment]
Could you send me the map you are trying to convert?

**Comment by AusarAtef** [comment]
Really sorry, I just noticed the reply but I ended up just tossing out the map and manually adding everything to make it work.
